# russian
а: a
б: b
в: v
г: g
д: d
е: e
ё: io
ж: j
з: z
и: i
й: yi
к: k
л: l
м: m
н: n
о: o
п: p
р: r
с: s
т: t
у: u
ф: f
х: h
ц: ts
ч: ch
ш: sh
щ: shch
ъ: i
ы: i
ь: i
э: ye
ю: u
я: ya
ă: a
î: i
ţ: t
â: a
ş: s

#polish
ę: e
ó: o
ą: a
ś: s
ł: l
ż: z
ź: z
ć: c
ń: n
